### ISSUE TITLE
Circuirt breaker pattern methods

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-service-discovery#13]
The circuit breaker pattern in sync world is:

```
try {
  String s = circuitBreaker.execute(block);
} catch(Exception e) {
  // Something went bad : the block failed OR the CB is open
}
```

and

```
// The block executed , if it did not the we get the "default" value
String s = circuitBreaker.execute(block, "default");
```

I don't see corresponding methods in the current CB methods.

**Comment by cescoffier** [comment]
Where did you find this API ? It's not the Hystrix one, and does not really follow the "circuit-breaker" model (if we can call this a model).

**Comment by cescoffier** [comment]
Typically, no exception should be thrown if the CB is open, but the fallback need to be called.

**Comment by vietj** [comment]
http://martinfowler.com/bliki/CircuitBreaker.html

_Calling the circuit breaker will call the underlying block if the circuit is closed, but return an error if it's open_

**Comment by cescoffier** [comment]
it's not the definition from the "Release it", neither how Hystrix works. If the circuit is open, it invokes the callback, that's all.

**Comment by vietj** [comment]
do you have a description of the release it ?

**Comment by cescoffier** [comment]
```
In the normal “closed” state, the circuit breaker executes operations as usual. These can be calls out to another system, or they can be internal operations that are subject to timeout or other execution failure. If the call succeeds, nothing extraordinary happens. If it fails, however, the circuit breaker makes a note of the failure. Once the number of failures (or frequency of failures, in more sophisticated cases) exceeds a threshold, the circuit breaker trips and “opens” the circuit. When the circuit is “open,” calls to the circuit breaker fail immediately, without any attempt to execute the real operation. After a suitable amount of time, the circuit breaker decides that the operation has a chance of succeeding, so it goes into the “half-open” state. In this state, the next call to the circuit breaker is allowed to execute the dangerous operation. Should the call succeed, the circuit breaker resets and returns to the “closed” state, ready for more routine operation. If this trial call fails, however, the circuit breaker returns to the “open” state until another timeout elapses.
```

But actually I agree that throwing an exception when the circuit is open may actually be useful to detect that the circuit is open. I don't know if this exception should be thrown when a fallback is set (because actually executing the fallback denotes that the circuit is open). 

So if could be something like (the exception would be a runtime exception)

```
// Throws an exception if the circuit is open
CircuitBreaker executeBlocking(Handler<Void> code) throws CircuitOpenException
// Execute the fallback if the circuit is open, no exception thrown
CircuitBreaker executeBlockingWithFallback(Handler<Void> code, Handler<Void> fallback);
```

Right now, these methods are called `executeBlocking` (after a discussion with you and Tim). I'm still not happy with this name as I found it confusing with the `vertx.executeBlocking` construct. It's more an `executeSync` kind of thing.

I'm also note sure we should have these method. Circuit breaker are there to control the communication with some _external_ entities. This interaction should be asynchronous. These methods may encourage a synchronous communication with external entities, which we should avoid.

**Comment by cescoffier** [comment]
1. The "executeBlocking" method has been removed.
2. The circuit breaker has now a new API based on `Future`
3. The code has been moved to https://github.com/vert-x3/vertx-circuit-breaker
