### ISSUE TITLE
ServiceReference#get method does not rewrap the service

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-service-discovery#14]
The method decl `<T> T get()` does not allow code generation to rewrap the type and it merely returns the object.

**Comment by cescoffier** [comment]
Yes, but there is nothing that can be done there. How the type rewriting works require code generation, here we can't.

**Comment by vietj** [comment]
hum that's not a valid answer :-)

**Comment by cescoffier** [comment]
Yes, but it's technically impossible to get it right. The code does not know how is name the "whatever wrapped object". The only knowledge of this it's in the code generator.

**Comment by vietj** [comment]
I've drafted a solution for this.

**Comment by cescoffier** [comment]
The drafter solution requires using the service type to retrieve the service object. It should not be the case when using service references.

I've done another solution based on the latest codegen improvements (that remove the limitation mentioned in my first comment).

Still stuck because of https://github.com/vert-x3/vertx-rx/issues/71
