### ISSUE TITLE
Consider merging AsyncMap with version in vertx-core

### ISSUE THREAD

**Issue by aschrijver** [vert-x3/vertx-service-discovery#41]
I am considering using this version of `AsyncMap` in another vertx project, that does not depend on servicediscovery.

Was wondering why you chose to implement this version of `AsyncMap` and didn't go with what's in vertx-core (I assume for reasons of simplicity). Now you have 2 similarly named classes that are incompatible, yet share a bunch of similar code. I would have to copy this class to my own project to re-use it.

Can this possibly be merged with the existing AsyncMap stuff in vertx-core? I.e. implement https://github.com/eclipse/vert.x/blob/3c340faf6d3edee23026786da7b9fbe28c4ed509/src/main/java/io/vertx/core/shareddata/AsyncMap.java and add the implementation to `io.vertx.core.shareddata.impl`.

**Comment by cescoffier** [comment]
This version is quite specific. It delegates to a synchronous map, and depending wether or not the Vert.x node is clustered, use different **synchronous** map implementation. 

In cluster mode, it does not use Vert.x `AsyncMap` but delegates to a clustered sync map. This is because I needed operations to retrieve the set of keys (not possible in the Vert.x async map), as well as a `getAll` operation to retrieve the map (copy). 

Maybe we can add an operation to retrieve the keys and values in vert.x core `AsyncMap`.

**Comment by aschrijver** [comment]
Yeah, sorry, I wasn't all that clear when I said '...existing AsyncMap stuff in core'. I meant collecting this similar functionality in the package structure of core, in a consistent way, and maybe do some renaming, adding of additional classes, etc. to make it intuitive and conceptually sound.

**Comment by cescoffier** [comment]
It would make sense, but we don't want classes in core not used in core (we don't want vert.x core to have the size of Guava ;-)). It could be a kind of compendium library, but it won't contain the vert.x core classes.

About the one used here, do you really think they have potential usage outside of hits project. They are quite specific.

**Comment by aschrijver** [comment]
Yes I do. Look at Issues project..
Posted couple of ideas there related to modularization of core.
I have lots of plans for Vert.x!

**Comment by cescoffier** [comment]
It's probably better to track the effort on https://github.com/vert-x3/issues/issues. Then, I can move these class into the library.

**Comment by aschrijver** [comment]
No I cannot at the moment. Pls connect with me on LinkedIn and I tell you a bit more.
